from textwrap import wrap
import subprocess
file = input("Filename: ")
f = open(f"{file}", "r")
txt = f.read().upper()
f.close()
txt = wrap(txt, 2)
txt = str(txt).replace("'", "")
txt = str(txt).replace("[", "")
txt = str(txt).replace("]", "")
txt = str(txt).replace(",", "")
print(str(txt))
o = open(file, "w")
o.write(str(txt))
o.close()
